import { Message } from 'api/task';

export const messageMock: Message[] = [
  {
    chunk_id: 1,
    speaker_name: '凯尔希',
    content: '大家好，欢迎来到今天的圆桌讨论！',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_001.mp3',
  },
  {
    chunk_id: 2,
    speaker_name: '阿米娅',
    content: '很高兴见到大家！',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_002.mp3',
  },
  {
    chunk_id: 3,
    speaker_name: '陈',
    content: '今天的话题非常有趣，让我们开始讨论吧。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_003.mp3',
  },
  {
    chunk_id: 4,
    speaker_name: '赫默',
    content: '我同意，这个议题值得深入探讨。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_004.mp3',
  },
  {
    chunk_id: 5,
    speaker_name: '夜莺',
    content: '从医学角度来看，这确实是一个重要问题。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_005.mp3',
  },
  {
    chunk_id: 6,
    speaker_name: '银灰',
    content: '商业层面的考量也不容忽视。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_006.mp3',
  },
  {
    chunk_id: 7,
    speaker_name: '闪灵',
    content: '让我们听听不同的观点。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_007.mp3',
  },
  {
    chunk_id: 8,
    speaker_name: '史尔特尔',
    content: '我觉得这个方案可行性很高。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_008.mp3',
  },
  {
    chunk_id: 9,
    speaker_name: '艾雅法拉',
    content: '数据分析显示这个趋势很明显。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_009.mp3',
  },
  {
    chunk_id: 10,
    speaker_name: '伊芙利特',
    content: '我有不同的看法，让我解释一下。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_010.mp3',
  },
  {
    chunk_id: 11,
    speaker_name: '塞雷娅',
    content: '安全性是我们必须考虑的首要因素。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_011.mp3',
  },
  {
    chunk_id: 12,
    speaker_name: '凯尔希',
    content: '这个观点很有价值，请继续。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_012.mp3',
  },
  {
    chunk_id: 13,
    speaker_name: '阿米娅',
    content: '我们需要平衡各方的利益。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_013.mp3',
  },
  {
    chunk_id: 14,
    speaker_name: '能天使',
    content: '技术实现上应该没有太大问题。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_014.mp3',
  },
  {
    chunk_id: 15,
    speaker_name: '德克萨斯',
    content: '时间线需要重新规划。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_015.mp3',
  },
  {
    chunk_id: 16,
    speaker_name: '拉普兰德',
    content: '我觉得还有其他的解决方案。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_016.mp3',
  },
  {
    chunk_id: 17,
    speaker_name: '红',
    content: '让我们回到问题的核心。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_017.mp3',
  },
  {
    chunk_id: 18,
    speaker_name: '推进之王',
    content: '资源分配需要更合理的安排。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_018.mp3',
  },
  {
    chunk_id: 19,
    speaker_name: '斯卡蒂',
    content: '我支持这个决定。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_019.mp3',
  },
  {
    chunk_id: 20,
    speaker_name: '幽灵鲨',
    content: '让我们总结一下今天的讨论要点。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_020.mp3',
  },
  {
    chunk_id: 21,
    speaker_name: '凯尔希',
    content: '感谢大家的积极参与，今天的圆桌讨论到此结束。',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_021.mp3',
  },
  {
    chunk_id: 22,
    speaker_name: '阿米娅',
    content: '期待下次再见！',
    url: 'https://torappu.prts.wiki/assets/audio/voice/char_002_amiya/cn_022.mp3',
  },
];
